name: CI/CD Pipeline for LMS Back-End

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      UPLOAD_DIR: /opt/apache/apache-tomcat-10.1.1/webapps

    steps:
      - name: Checking out the latest version from the repository
        uses: actions/checkout@v3

      - name: Setting up the Java JDK
        uses: actions/setup-java@v3.6.0
        with:
          java-version: 11
          distribution: adopt

      - name: Packaging the web application
        run: mvn package

      - name: 'Authenticate to the GCP'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.SERVICE_ACCOUNT_PRIVATE_KEY }}'

      - name: 'Setting up the gcloud'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: Cleaning up the old stuff
        run: >
          gcloud compute ssh --zone="asia-south1-a" dep-9-vm 
          --command="sudo rm -rf $UPLOAD_DIR/lms#api.war $UPLOAD_DIR/lms#api"

      - name: 'Deploying the war file'
        run: gcloud compute scp --zone="asia-south1-a" target/lms#api.war root@dep-9-vm:$UPLOAD_DIR

